from Embark.services.agent_executors.executor import AgentExecutor


class LangGraphExecutor(AgentExecutor):
    async def register_agent():
        ...
    async def get_agents_for_workflow():
        ...
    async def initialize_reflection():
        ...
    async def execute():
        ...